### ISSUE TITLE
Pycharm/IDE linter issue: Expected type 'NDArray | NDArray', got 'ndarray' instead

### ISSUE THREAD

**Issue by caniko** [cheind/pydantic-numpy#2]
This issue occurs when trying to return `NDArray` from a function:
```python
def my_func() -> NDArray:
    return np.array([1, 1])
```
Version:
```
np.__version__
Out[3]: '1.22.4'
```

**Comment by cheind** [comment]
I believe that's addressed by your PR?

**Comment by caniko** [comment]
No, unfortunately 😞

**Comment by cheind** [comment]
ok, got it

**Comment by caniko** [comment]
Hello, I fixed this over at my [fork](https://github.com/caniko/pydantic-numpy).
