### ISSUE TITLE
Developer setup 

### ISSUE THREAD

**Issue by danieljfarrell** [cheind/pydantic-numpy#6]
Hi!

Not used Poetry before.

I want to make a developer environment for running tests. Normally would so this with a dev_requirements.txt file. 

How do you make a developer setup.

So far I made a new virtual environment.

Did `pip install poetry` and `poetry install`.

I tried to run pytest but it was not installed.

So I did `pip install pytest`.

Which revealed Numpy was not installed!

So after doing `pip install numpy pydantic` I could run the tests. Is there a Poetry was of doing this easily that I am missing?

**Comment by cheind** [comment]
Hey, I haven't been using poetry in a while, but you might want to checkout the workflow file

https://github.com/cheind/pydantic-numpy/blob/main/.github/workflows/python-package.yml

on how we run the automated tests

**Comment by cheind** [comment]
I think we might close this.
